# Generated by Django 3.1 on 2020-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SECRET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECRET_KEY', models.CharField(max_length=200)),
                ('DEBUG', models.CharField(max_length=200)),
                ('DB_DEFAULT_ENGINE', models.CharField(max_length=200)),
                ('DB_DEFAULT_NAME', models.CharField(max_length=200)),
            ],
        ),
    ]
